type OptionChainDto
{
    price:Float
    openInterest:Int
    time:String
    strikePrice:String
}
input OptionChainInputDto
{
    id:Int
    price:Float
    openInterest:Int
    time:String
    strikePrice:String
    index:String
    impliedVolatility:Float
    underlyingValue:Int
    daysLeftToExpire:Int
    totalTradedVolume:Int
}
type OptionChainForStrikePriceDto{
    callPriceList:[Float]
    callOpenInterestList:[Int]
    callTimeList:[String]
    putPriceList:[Float]
    putOpenInterestList:[Int]
    putTimeList:[String]
    overallChangeInOIList:[Int]
}
type OIChangeDto{
    oiChangeList:[Int]
    timeList:[String]
}

type StrikePriceOutputDto{
    strikePrice:String
    delta:Float
    theta:Float
    gamma:Float
    vega:Float
    volume:Int
}

type Query{
    getOptionChainData : [OptionChainDto]
    getOptionChainDataForStrikePrice(strikePrice:Int):OptionChainForStrikePriceDto
    getChangeInOIForIndex(index:String):OIChangeDto
    getDataForStrikePriceSelection(indexType:String,actionType:String,optionType:String):[StrikePriceOutputDto]
}
type Mutation{
    saveOptionChainData(optionChainInputDtos:[OptionChainInputDto]) : Boolean
}
